export const UPDATE_JUTTLE_SOURCE = 'UPDATE_JUTTLE_SOURCE';
export const UPDATE_PROGRAM_STATE = 'UPDATE_PROGRAM_STATE';
export const UPDATE_FLOWGRAPH = 'UPDATE_FLOWGRAPH';
export const NODE_EMIT_POINT = 'NODE_EMIT_POINT';
export const NODE_CONSUME_POINT = 'NODE_CONSUME_POINT';
export const UPDATE_UNDO_INDEX = 'UPDATE_UNDO_INDEX';
export const RESET = 'RESET';
